<?php
$users = [
    [
        'lastname'=>'1Ladmin',
        'name'=>'Jean',
        'pseudo'=>'jeanjean',
        'email'=>'jladmin@gmail.com',
        'status'=>'administrateur'
    ],
    [
        'lastname'=>'2Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'3Legameur',
        'name'=>'Aristide',
        'pseudo'=>'GG34',
        'email'=>'Aristid.goat@gmail.com',
        'status'=>'joueur'
    ],
    [
        'lastname'=>'4Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'5Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'6Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'7Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'8Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'9Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'10Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'11Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'12Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'13Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'14Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'15Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'16Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'17Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'18Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'19Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'20Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'21Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'M\'Bappe',
        'name'=>'Kylian',
        'pseudo'=>'kyky07',
        'email'=>'K.mbappe@gmail.com',
        'status'=>'joueur'
    ],
    [
        'lastname'=>'Sissi',
        'name'=>'Princesse',
        'pseudo'=>'Sissi_du_93',
        'email'=>'P.sissi@gmail.com',
        'status'=>'joueur'
    ],
    [
        'lastname'=>'Sawyer',
        'name'=>'Tom',
        'pseudo'=>'tomtom',
        'email'=>'tSawyer@gmail.com',
        'status'=>'joueur'
    ],
    [
        'lastname'=>'Coffee',
        'name'=>'john',
        'pseudo'=>'cofcof',
        'email'=>'j.coffee@gmail.com',
        'status'=>'joueur'
    ],
];

$totalUsers=count($users);    // On compte le nombre d'utilisateurs total

// On compte le nombre d'admin, de modérateur et de joueurs . source : https://stackoverflow.com/a/53308963
$totalAdmin = array_count_values(array_column($users, 'status'))['administrateur'];
$totalMod = array_count_values(array_column($users, 'status'))['modérateur'];
$totalGamer = array_count_values(array_column($users, 'status'))['joueur'];
    


?>